### ISSUE TITLE
[PAW] Update of all content, including dynamic content on real results screens

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16238]
## Description
* Updating all content across the wizard
* Add dynamic content on the real results screens
* Remove the SM results screens.

### User story

**AS A** Veteran or other user of the PACT Act Wizard
**I WANT** to see updated, dynamic content in the website
**SO THAT** as I answer the questions, the content is applicable to the questions answered, and the results screen displays according to the logic/my answers.

### Artifacts
Danielle's document [sharepoint ](https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EexjTD76bnVOl8snKt6nK5gBzGoQbo5zugMpjwOBDw7Tjg?e=9NV82P)document

## Acceptance criteria
- [x] All content has been updated per Danielle's most recent document
- [x] Dynamic content displays on the real results screens
- [x] No Survey Monkey screens exist in the build

**Comment by randimays** [comment]
I have implemented all the content, but I have unit tests to add and manual testing to do. This will carry over due to needing code review and a11y/design review as well before merging.

**Comment by randimays** [comment]
PR posted for review [here](https://dsva.slack.com/archives/C52CL1PKQ/p1701809064656549)

**Comment by DanielleThierryUSDSVA** [comment]
Hi, @randimays! As I said in slack, this is so good. I'm going through each flow and screen against the Word doc just as a content QA. I'll note edits in this ticket. First chunk is below. 

I also want to note that several of these are tiny content things (like a missing word or capped letter that should be lowercase) that have carried over from the Word doc and I'm noticing them on the screen as I look through. So I'm also correcting those in the Word doc as I spot them. 

- Breadcrumb: Change to match H1 
- Screen 1: "Get PACT Act information for survivors" link: Update to  https://www.va.gov/resources/the-pact-act-and-your-va-benefits/#information-for-survivors
- In this screen, bold the highlighted dates.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/62957278/71ce19cd-a3e0-4ce0-85e8-8434c47ddaa6)
- Burn pit flow > Results screen 2 > presumptive conditions accordion: Lowercase the "b" in "burn pits".
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/62957278/914036c2-9831-4d1c-8a69-fcaf7a24a2e9)
- Agent Orange flow > Results screen 1 > dynamic content for "The waters in or around Vietnam" for S2.2: Add the word "between" to read "waters between January"...
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/62957278/58a94440-cca3-44eb-a2f8-e8ab4de1e0fd)

**Comment by DanielleThierryUSDSVA** [comment]
Rest of my comments:

- Agent Orange flow > Results screen 1 > dynamic content for "American Samoa or its territorial waters" for S2.2.1: Add the word "from" to read "waters from January"
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/62957278/8321419e-60c7-4d89-a75b-7d32ab3e7c92)
- Agent Orange flow > Results screen 1 >  dynamic content for "The response to an Air Force B-52 bomber fire near Thule Air Force base in Greenland for S2.3": Remove "2022"
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/62957278/410aaf8e-103b-46f9-af61-887132559ffb)

And then I have one design question I want to get Amanda's opinion on in the morning. I'll follow up tomorrow and let you know any last tweak based on that. Thank you again!

**Comment by cindymerrill** [comment]
@randimays Re 1, the link still doesn't work for me. This is what I see: 
<img width="649" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/69914583/a26cec9e-a7c3-4226-a370-dbb538864c4b">
@DanielleThierryUSDSVA provided a link in her comment above, which may or may not be the same as you have.

Re 2, Danielle also requested that the years be bolded, so she could discuss it more with you.

Re 3, bummer.

**Comment by randimays** [comment]
@cindymerrill I spaced on this one last week, but just remembered.

> 1. Broken link, but maybe that’s because it points to something on Prod? It’s the [Get PACT Act information for survivors](http://preview-prod.vfs.va.gov/preview?nodeId=47278#information-for-survivors) link on the intro page.

> Re 1, the link still doesn't work for me. This is what I see:

In order to see any pages in the CMS, you need to have SOCKS access. `preview-prod.vfs.va.gov` is a Drupal link.

**Comment by randimays** [comment]
@DanielleThierryUSDSVA I have addressed all of your requested changes so far (with the exception of bolding on the service period question). I'll keep an eye out for the changes to results screen 2 today. Thank you!

**Comment by FranECross** [comment]
@randimays When I'm viewing this page [Get PACT Act information for survivors](http://preview-prod.vfs.va.gov/preview?nodeId=47278#information-for-survivors), and I've expanded the section "What other benefits are survivors eligible for?", there's a link "Learn more about family member benefits", but when I click it, I see this error. Thanks in advance!
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/147188767/39ee91d3-0a9a-4f04-b70c-634c344e1122)


![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/147188767/f130f03b-d440-4d34-b1fa-0ce375d3f1e3)

**Comment by randimays** [comment]
@FranECross this change hasn't been pushed to staging yet, but Danielle gave me an updated link for `Get PACT Act information for survivors`: https://www.va.gov/resources/the-pact-act-and-your-va-benefits/#information-for-survivors. The `Learn more about family member benefits` link is fixed in that one. The previous link for `Get PACT Act information for survivors` was an unpublished page, so it's not unusual that there were broken links in it.

**Comment by jilladams** [comment]
@randimays the vets-website PR listed upthread merged 2 weeks ago -- was that the last change? Or is there more outstanding here?

**Comment by jilladams** [comment]
Closing based on existing review from Cindy / Danielle, per convo with Fran.

**Comment by randimays** [comment]
@jilladams @FranECross I was waiting on some more content changes from Danielle, and I still have a WIP branch for adjustments from her previous feedback. I'll work on getting that branch merged in today, and I [checked in on Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1703088156258859?thread_ts=1702404832.197869&cid=C52CL1PKQ) to see if she has those content changes ready for me.

**Comment by jilladams** [comment]
@randimays could you also add a link to your newer PR? It's not showing up on here AFAICT.

**Comment by randimays** [comment]
No worries @jilladams, appreciate you moving my tickets along for me! [Here's the WIP PR](https://github.com/department-of-veterans-affairs/vets-website/pull/27235)

**Comment by randimays** [comment]
PR in the above comment is ready for review. [Posted here](https://dsva.slack.com/archives/C52CL1PKQ/p1703186815174359).

**Comment by jilladams** [comment]
Closing per https://dsva.slack.com/archives/C52CL1PKQ/p1703199744951859?thread_ts=1702404832.197869&cid=C52CL1PKQ

We'll cut new tickets for add'l content updates
